class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'fr': {
      'nav.public.fr': 'FR',
      'nav.public.en': 'EN',
      'nav.donor.home': 'Accueil',
      'nav.donor.map': 'Localisation',
      'nav.donor.history': 'Historique',
      'nav.donor.profile': 'Profil',
      'nav.hospital.dashboard': 'Dashboard',
      'nav.hospital.requests': 'Demandes',
      'nav.hospital.stats': 'Statistiques',
      'nav.hospital.map': 'Localisation',
      'nav.hospital.profile': 'Profil',
      'nav.admin.dashboard': 'Dashboard',
      'nav.admin.hospitals': 'Hôpitaux',
      'nav.admin.users': 'Utilisateurs',
      'nav.admin.reports': 'Rapports & Stats',
      'auth.login.title': 'Connexion',
      'auth.login.subtitle': 'Accédez à votre espace SangVie',
      'auth.login.identifier': 'Email ou téléphone',
      'auth.login.password': 'Mot de passe',
      'auth.login.forgot': 'Mot de passe oublié ?',
      'auth.login.submit': 'Se connecter',
      'auth.login.noAccount': 'Pas encore de compte ?',
      'auth.login.createAccount': 'Créer un compte',
      'auth.register.title': 'Inscription',
      'auth.register.subtitle': 'Créez votre compte SangVie',
      'auth.register.donorTab': 'Donneur',
      'auth.register.hospitalTab': 'Hôpital',
      'auth.register.hospitalName': "Nom de l'hôpital",
      'auth.register.hospitalId': "Numéro d'identification",
      'auth.register.hospitalEmail': 'Email institutionnel',
      'auth.register.fullName': 'Nom complet',
      'auth.register.phone': 'Numéro de téléphone',
      'auth.register.password': 'Mot de passe',
      'auth.register.passwordConfirm': 'Confirmer le mot de passe',
      'auth.register.submit': 'Créer mon compte',
      'auth.register.already': 'Vous avez déjà un compte ?',
      'auth.register.login': 'Se connecter',
      'auth.forgot.title': 'Mot de passe oublié',
      'auth.forgot.subtitle': 'Entrez votre email ou numéro de téléphone pour réinitialiser votre mot de passe',
      'auth.forgot.identifier': 'Email ou téléphone',
      'auth.forgot.submit': 'Envoyer le lien',
      'auth.forgot.backToLogin': 'Retour à la connexion',
      'auth.forgot.sentTitle': 'Email envoyé !',
      'auth.forgot.sentDescription': 'Nous avons envoyé un lien de réinitialisation à {identifier}. Vérifiez votre boîte de réception.',
      'auth.forgot.notReceived': "Vous n'avez pas reçu l'email ?",
      'auth.forgot.resend': 'Renvoyer',
    },
    'en': {
      'nav.public.fr': 'FR',
      'nav.public.en': 'EN',
      'nav.donor.home': 'Home',
      'nav.donor.map': 'Map',
      'nav.donor.history': 'History',
      'nav.donor.profile': 'Profile',
      'nav.hospital.dashboard': 'Dashboard',
      'nav.hospital.requests': 'Requests',
      'nav.hospital.stats': 'Statistics',
      'nav.hospital.map': 'Map',
      'nav.hospital.profile': 'Profile',
      'nav.admin.dashboard': 'Dashboard',
      'nav.admin.hospitals': 'Hospitals',
      'nav.admin.users': 'Users',
      'nav.admin.reports': 'Reports & Stats',
      'auth.login.title': 'Sign in',
      'auth.login.subtitle': 'Access your SangVie space',
      'auth.login.identifier': 'Email or phone number',
      'auth.login.password': 'Password',
      'auth.login.forgot': 'Forgot password?',
      'auth.login.submit': 'Sign in',
      'auth.login.noAccount': 'No account yet?',
      'auth.login.createAccount': 'Create an account',
      'auth.register.title': 'Sign up',
      'auth.register.subtitle': 'Create your SangVie account',
      'auth.register.donorTab': 'Donor',
      'auth.register.hospitalTab': 'Hospital',
      'auth.register.hospitalName': 'Hospital name',
      'auth.register.hospitalId': 'Identification number',
      'auth.register.hospitalEmail': 'Institutional email',
      'auth.register.fullName': 'Full name',
      'auth.register.phone': 'Phone number',
      'auth.register.password': 'Password',
      'auth.register.passwordConfirm': 'Confirm password',
      'auth.register.submit': 'Create my account',
      'auth.register.already': 'Already have an account?',
      'auth.register.login': 'Sign in',
      'auth.forgot.title': 'Forgot password',
      'auth.forgot.subtitle': 'Enter your email or phone number to reset your password',
      'auth.forgot.identifier': 'Email or phone',
      'auth.forgot.submit': 'Send link',
      'auth.forgot.backToLogin': 'Back to sign in',
      'auth.forgot.sentTitle': 'Email sent!',
      'auth.forgot.sentDescription': 'We have sent a reset link to {identifier}. Please check your inbox.',
      'auth.forgot.notReceived': "Didn't receive the email?",
      'auth.forgot.resend': 'Resend',
    },
  };
}
